# Generated by Django 5.2.7 on 2025-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='getnet_auth_code',
            field=models.CharField(blank=True, help_text='Código de autorización bancario (Autorización)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='getnet_request_id',
            field=models.CharField(blank=True, help_text='ID de solicitud de sesión enviado a Getnet (Reference)', max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='getnet_transaction_id',
            field=models.CharField(blank=True, help_text='ID de transacción final devuelto por Getnet (Webhook)', max_length=150, null=True),
        ),
    ]
