# Generated by Django 5.2.7 on 2025-11-30 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_guardianprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardianrelation',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relations', to=settings.AUTH_USER_MODEL),
        ),
    ]
