# Generated by Django 5.2.7 on 2025-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_guardianprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='cuotas_ids',
        ),
        migrations.AddField(
            model_name='payment',
            name='getnet_token',
            field=models.CharField(blank=True, help_text='Token de transacción recibido al crear la sesión (lo usa el webhook)', max_length=120, null=True),
        ),
    ]
